### PR TITLE
impr: Ghibli API

### PR DESCRIPTION
**Pull request by mezotv**
This adds a new API that has more information including the new ghibli movies

### CODE REVIEW

**Comment by emamaria** [comment]
Thank you very much for your request.

Although your request can add extra information to my project, for personal reasons I don't want to add any contributions in the project but my self for now.

Thank you.

My Best regards.

**Comment by mezotv** [comment]
@emamaria Could you take a look at my pr?

**Comment by emamaria** [comment]
@mezotv Thank you very much for your request. I appreciate it.

Although your request can add extra information to my project, for personal reasons I don't want to add any contributions in the project but my self for now.

Thank you
 
My Best regards.

**Comment by emamaria** [comment]
@mezotv Thank you very much for your request. I appreciate it.

Although your request can add extra information to my project, for personal reasons I don't want to add any contributions in the project but my self for now.

Thank you

My Best regards.

**Pull request closed without merging**
